name: build-and-deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: Clone and Build
        run: |
          npm install
          npm install -g gulp-cli
          gulp build
      - uses: actions/upload-artifact@v2
        with:
          name: website-build
          path: |
              build
  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: website-build
          path: /tmp/website-build
      - uses: actions/checkout@v2
      - name: Deploy website
        if: github.event_name == 'push'
        run: |
          export ROOT=$(pwd)
          cd /tmp/website-build/
          git init
          cp $ROOT/.git/config ./.git/config
          git add .
          git config --local user.email "push@gha"
          git config --local user.name "GHA"
          git commit -am "update ${{ github.sha }}"
          git push -u origin +HEAD:gh-pages

