name: Docs

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:


  Landing:
    runs-on: ubuntu-latest
    name: '🗺️ Landing'
    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v2

      - name: '🛠️ Setup NodeJS'
        uses: actions/setup-node@v2
        with:
          node-version: '10'

      - name: Build
        run: |
          cd site
          npm install
          npm install -g gulp-cli
          gulp build

      - name: '📤 Upload artifact: Landing HTML'
        uses: actions/upload-artifact@v2
        with:
          name: Landing-HTML
          path: site/build


  Sphinx:
    runs-on: ubuntu-latest
    name: '📓 Docs'
    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: 🛠️ Setup environment
        run: |
          sudo apt update -qq
          sudo apt install -y make
          make env

      - name: 📓 Build the documentation
        run: |
          . ./env/conda/bin/activate f4pga-docs
          make html

      - name: '📤 Upload artifact: Sphinx HTML'
        uses: actions/upload-artifact@v2
        with:
          name: Documentation-HTML
          path: _build/html


  Deploy:
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    name: '🚀 Deploy to GitHub Pages'
    runs-on: ubuntu-latest
    needs:
      - Landing
      - Sphinx
    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v2

      - name: '📥 Download Artifact: Landing HTML'
        uses: actions/download-artifact@v2
        with:
          name: Landing-HTML
          path: Site-HTML

      - name: '📥 Download Artifact: Documentation HTML'
        uses: actions/download-artifact@v2
        with:
          name: Documentation-HTML
          path: Site-HTML/docs

      - name: Deploy website
        run: |
          cd Site-HTML
          touch .nojekyll
          echo 'f4pga.org' > CNAME
          git init
          cp ../.git/config ./.git/config
          git add .
          git config --local user.email "push@gha"
          git config --local user.name "GHA"
          git commit -am "update ${{ github.sha }}"
          git push -u origin +HEAD:gh-pages
          cd ..
          rm -rf Site-HTML
